# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
wally = "UpliftGames/wally@0.3.1"
luau-lsp = "JohnnyMorganz/luau-lsp@1.27.1"
stylua = "JohnnyMorganz/stylua@0.20.0"
lune = "filiptibell/lune@0.8.0"
rojo = "rojo-rbx/rojo@7.4.0"
# rojo = "rojo-rbx/rojo@7.3.0"