column_width = 140
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 4
quote_style = "ForceSingle"
call_parentheses = "None"
collapse_simple_statement = "Never"

[sort_requires]
enabled = false