[package]
name = "data-oriented-house/squash"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"
authors = ["Sona"]

description = "A comprehensive and flat library for compressing and decompressing data, optimized for minimizing size."

realm = "shared"

exclude = ["**"]
include = [
    "src/Squash.luau",
    "LICENSE",
    "wally.toml",
]

[dependencies]