[package]
name = "data-oriented-house/squash"
version = "1.1.6"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"
authors = ["Sona"]

description = "A comprehensive and flat library for compressing and decompressing data, optimized for minimizing size."

realm = "shared"

exclude = ["**"]
include = [
    "default.project.json",
    "src",
    "src/**",
    "LICENSE",
    "wally.toml",
]

[dependencies]