--!strict

local Squash = require(game.ReplicatedStorage.Squash)
local test = require(game.ReplicatedStorage.test)

test.Axes()
test.CFrame(Squash.uint)
test.CFrame(Squash.number)
test.CFrame(Squash.number)
test.CatalogSearchParams(Squash.english)
test.Color3(Squash.uint)
test.Color3(Squash.number)
test.Color3(Squash.number)
test.ColorSequence()
test.ColorSequenceKeypoint()
test.DateTime()
test.DockWidgetPluginGuiInfo()
test.Enum()
test.EnumItem()
test.Faces()
test.FloatCurveKey()
test.Font()
test.NumberRange(Squash.uint)
test.NumberRange(Squash.number)
test.NumberRange(Squash.number)
test.NumberSequenceKeypoint(Squash.uint)
test.NumberSequenceKeypoint(Squash.number)
test.NumberSequenceKeypoint(Squash.number)
test.NumberSequence(Squash.uint)
test.NumberSequence(Squash.number)
test.NumberSequence(Squash.number)
test.OverlapParams()
test.PathWaypoint(Squash.uint)
test.PathWaypoint(Squash.number)
test.PathWaypoint(Squash.number)
test.PhysicalProperties(Squash.uint)
test.PhysicalProperties(Squash.number)
test.PhysicalProperties(Squash.number)
test.Ray(Squash.uint)
test.Ray(Squash.number)
test.Ray(Squash.number)
test.RaycastParams()
test.RaycastResult(Squash.uint)
test.RaycastResult(Squash.number)
test.RaycastResult(Squash.number)
test.Rect()
test.Region3(Squash.uint)
test.Region3(Squash.number)
test.Region3(Squash.number)
test.Region3int16(Squash.uint)
test.Region3int16(Squash.number)
test.Region3int16(Squash.number, 4)
test.TweenInfo(Squash.uint)
test.TweenInfo(Squash.number)
test.TweenInfo(Squash.number)
test.UDim(Squash.uint)
test.UDim(Squash.number)
test.UDim(Squash.number)
test.UDim2(Squash.uint)
test.UDim2(Squash.number)
test.UDim2(Squash.number)
test.Vector2(Squash.uint)
test.Vector2(Squash.number)
test.Vector2(Squash.number)
test.Vector2int16(Squash.uint)
test.Vector2int16(Squash.number)
test.Vector2int16(Squash.number, 4)
test.Vector3(Squash.uint)
test.Vector3(Squash.number)
test.Vector3(Squash.number)
test.Vector3int16(Squash.uint)
test.Vector3int16(Squash.number)
test.Vector3int16(Squash.number, 4)