--!strict

local Squash = require(script.Parent)
local test = require(script.Parent.test)

-- test.Axes()
-- test.CFrame(Squash.uint)
-- test.CFrame(Squash.int)
-- test.CFrame(Squash.number)
-- test.CatalogSearchParams(Squash.english)
-- test.Color3(Squash.uint)
-- test.Color3(Squash.int)
-- test.Color3(Squash.number)
-- test.ColorSequence()
-- test.ColorSequenceKeypoint()
-- test.DateTime()
-- test.DockWidgetPluginGuiInfo()
-- test.Enum()
-- test.EnumItem()
-- test.Faces()
-- test.FloatCurveKey()
-- test.Font()
-- test.NumberRange(Squash.uint)
-- test.NumberRange(Squash.int)
-- test.NumberRange(Squash.number)
-- test.NumberSequenceKeypoint(Squash.uint)
-- test.NumberSequenceKeypoint(Squash.int)
-- test.NumberSequenceKeypoint(Squash.number)
-- test.NumberSequence(Squash.uint)
-- test.NumberSequence(Squash.int)
-- test.NumberSequence(Squash.number)
-- test.OverlapParams()
test.PathWaypoint(Squash.uint)
test.PathWaypoint(Squash.int)
test.PathWaypoint(Squash.number)
test.PhysicalProperties(Squash.uint)
test.PhysicalProperties(Squash.int)
test.PhysicalProperties(Squash.number)
test.Ray(Squash.uint)
test.Ray(Squash.int)
test.Ray(Squash.number)
test.RaycastParams()
test.RaycastResult()
test.Rect()
test.Region3int16()
test.Region3(Squash.uint)
test.Region3(Squash.int)
test.Region3(Squash.number)